config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'my_page' => 'users#show', as: 'my_page'
  # resource :users, only: [:show] do
  #   collection do
  #     get "unsubscribe"
  #     patch "withdraw"
  #   end
  # end
  resources :trainings
  # 現状1対1のテーブルになってしまっているから不要
  # resources :training_details
  resources :bodies, except: [:show]
  resources :meals, except: [:show]
  resources :events, except: [:show]

end

app/models/training.rb
class Training < ApplicationRecord

  has_many :training_details, dependent: :destroy

  accepts_nested_attributes_for :training_details, allow_destroy: true

  validates :training_date, presence: true

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  def index
    @trainings = Training.where(user_id: current_user.id).page(params[:page]).per(30).order("training_date ASC")
  end

  def new
    @training = Training.new
    @training.training_details.build
    # render plain: render_to_string(partial: 'new', layout: false, locals: { event: @training })
  end

  def create
    @training = Training.new(training_params)
    @training.user_id = current_user.id
    if @training.save
      flash[:notice] = "登録しました"
      redirect_to trainings_path
    else
      flash[:alert] = "もう一度入力してください"
      render :new
    end
  end

  def show
  end

  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])
    if @training.update(training_params)
      flash[:notice] = "更新しました"
      redirect_to trainings_path
    else
      flash[:alert] = "もう一度入力してください"
      render :edit
    end
  end

  def destroy
    training = Training.find(params[:id])
    training.destroy
    flash[:notice] = "削除しました"
    redirect_to trainings_path
  end

  private
  def training_params
    params.require(:training).permit(:training_date, training_details_attributes: [:id, :training_name, :body_part, :weight, :repetition, :memo])
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with model:training, local:true do |f| %>
<!--if文で分岐、有酸素運動なら時間、距離、メモ、それ以外は以下の通り-->
<!--これだけTrainingモデル-->
  <div class="form-group col-md-3">
    <%= f.label :日付, class: 'control-label' %>
    <%= f.date_field :training_date, class: 'form-control' %>
  </div>
  <%= f.fields_for :training_details do |training_detail| %>
    <div class="form-group col-md-3">
      <%= training_detail.label :training_name, "種目名" %>
      <%= training_detail.text_field :training_name, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= training_detail.label :body_part, "部位" %>
      <%#= training_detail.select :body_part, TrainingDetail.body_parts_i18n.keys.map{|k| [I18n.t("enums.training_detail.body_part.#{k}"), k]}, class: 'form-control' %>
      <%= training_detail.select :body_part, TrainingDetail.body_parts_i18n.invert, {prompt: false}, class:"form-control col-6"  %>
    </div>
    <div class="form-group col-md-3">
      <%= training_detail.label :weight, "重さ" %>
      <%= training_detail.number_field :weight, step: '0.1', min: '0', class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= training_detail.label :repetition, "回数" %>
      <%= training_detail.number_field :repetition, min: '0', class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= training_detail.label :memo, "メモ" %>
      <%= training_detail.text_field :memo, class: 'form-control' %>
    </div>
  <% end %>

  <div class="form-group col-md-3">
    <%= f.submit '登録', class: 'btn btn-info' %>
  </div>

<% end %>

app/views/trainings/_new.html.erb
<!--カレンダーのモーダル表示用　保留中-->

<div class="row">
<h1>トレーニング追加</h1>

<%= form_with model:@training, local:true do |f| %>

 <!--種目 -->

<!--if文で分岐、有酸素運動なら時間、距離、メモ、それ以外は以下の通り-->
  <div>
    <%= f.label :"重さ" %>
    <%= f.number_field :weight, autofocus: true %>
  </div>
  <div>
    <%= f.label :"回数" %>
    <%= f.number_field :repetition %>
  </div>
  <div>
    <%= f.label :"メモ" %>
    <%= f.text_field :memo %>
  </div>
  <div>
    <%= f.submit '登録' %>
  </div>

<% end %>
</div>

app/views/trainings/create.html.erb
<h1>Trainings#create</h1>
<p>Find me in app/views/trainings/create.html.erb</p>

app/views/trainings/destroy.html.erb
<h1>Trainings#destroy</h1>
<p>Find me in app/views/trainings/destroy.html.erb</p>

app/views/trainings/edit.html.erb
<h1>トレーニング内容編集</h1>
<%= render 'trainings/form', training: @training %>

app/views/trainings/index.html.erb
<!--<h1>筋トレカレンダー</h1>-->
<!--<div id="calendar"></div>-->

<!--<div class="modal fade" id="modal" tabindex="-1">-->
<!--	<div class="modal-dialog">-->
<!--		<div class="modal-content">-->
<!--			<div class="modal-header">-->
<!--				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>-->
<!--				<h4 class="modal-title">タイトル</h4>-->
<!--			</div>-->
<!--			<div class="modal-body">-->
<!--				本文-->
<!--			</div>-->
<!--			<div class="modal-footer">-->
<!--				<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>-->
<!--				<button type="button" class="btn btn-primary">ボタン</button>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->
<h1>トレーニング内容一覧</h1>
<table class="table table-striped table-hover">
	<thead class="thead-dark">
		<tr>
			<th>日付</th>
			<th>種目名</th>
			<th>部位</th>
			<th>重さ</th>
			<th>回数</th>
			<th>memo</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @trainings.each do |training| %>
			<tr>
				<td>
					<%= training.training_date.strftime('%Y/%m/%d') %>
				</td>
				<!--ここからネストされたtraninig_details modelの内容-->
				<% training.training_details.each do |training_detail| %>

					<td>
						<%= training_detail.training_name %>
					</td>
					<td>
						<%= training_detail.body_part_i18n %>
					</td>
					<td>
						<%= training_detail.weight %>kg
					</td>
					<td>
						<%= training_detail.repetition %>
					</td>
					<td>
						<%= training_detail.memo %>
					</td>

				<% end %>
	      <% if training.user_id == current_user.id %>
					<td>
						<%= link_to "編集", edit_training_path(training.id), class: 'btn btn-outline-success' %>
					</td>
					<td>
						<%= link_to "削除", training_path(training.id), method: :delete, data: {confirm: "削除しますか？"}, class: 'btn btn-outline-danger' %>
					</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
	<%= paginate @trainings %>

app/views/trainings/new.html.erb
<h1>トレーニング追加</h1>
<%= render 'trainings/form', training: @training %>

app/views/trainings/show.html.erb
<h1>Trainings#show</h1>
<p>Find me in app/views/trainings/show.html.erb</p>

app/views/trainings/update.html.erb
<h1>Trainings#update</h1>
<p>Find me in app/views/trainings/update.html.erb</p>