config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'my_page' => 'users#show', as: 'my_page'
  # resource :users, only: [:show] do
  #   collection do
  #     get "unsubscribe"
  #     patch "withdraw"
  #   end
  # end
  resources :trainings
  # 現状1対1のテーブルになってしまっているから不要
  # resources :training_details
  resources :bodies, except: [:show]
  resources :meals, except: [:show]
  resources :events, except: [:show]

end

app/models/body.rb
class Body < ApplicationRecord

  belongs_to :user

  attachment :image

  validates :weight, presence: true
  validates :record_date, presence: true, uniqueness: true

end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

  def index
    @bodies = Body.where(user_id: current_user.id).page(params[:page]).per(30).order("record_date ASC")
  end

  def new
    @body = Body.new
  end

  def create
    @body = Body.new(body_params)
    @body.user_id = current_user.id
    if @body.save
      flash[:notice] = "コミットでやんす!!"
      redirect_to bodies_path
    else
      flash[:alert] = "もう一度入力してください"
      render :new
    end
  end

  def edit
    @body = Body.find(params[:id])
  end

  def update
    @body = Body.find(params[:id])
    if @body.update(body_params)
      flash[:notice] = '更新しました'
      redirect_to bodies_path
    else
      flash[:alert] = 'もう一度入力してください'
      render :edit
    end
  end

  def destroy
    body = Body.find(params[:id])
    body.destroy
    flash[:notice] = '削除しました'
    redirect_to bodies_path
  end

  private
  def body_params
    params.require(:body).permit(:record_date, :weight, :bfp, :image)
  end

end

app/controllers/bodys_controller.rb
class BodysController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/views/bodies/_form.html.erb
<%= form_with model:body, local:true do |f| %>

  <div class="form-group col-md-3">
    <%= f.label :日付, class: 'control-label' %>
    <%= f.date_field :record_date, class: 'form-control' %>
  </div>

  <div class="form-group col-md-3">
    <%= f.label :weight, "体重(kg)" %>
    <%= f.number_field :weight, step: '0.1', min: '20', class: 'form-control' %>
  </div>

  <div class="form-group col-md-3">
    <%= f.label :bfp, "体脂肪率(％)" %>
    <%= f.number_field :bfp , step: '0.1', min: '0', class: 'form-control' %>
  </div>

  <div class="form-group col-md-3">
    <%= f.label :image, "カラダ写真" %>
    <%= f.attachment_field :image, class: "form-control-file" %>
  </div>
  <div class="form-group col-md-3">
    <%= f.submit '投稿', class: 'btn btn-info' %>
  </div>

<% end %>

app/views/bodies/edit.html.erb
<h1>体組成 編集</h1>
<%= render 'bodies/form', body: @body %>

app/views/bodies/index.html.erb
<h1>カラダ（体組成）</h1>

<table class="table table-striped table-hover">
	<tr>
		<th>日付</th>
		<th>体重(kg)</th>
		<th>体脂肪率(%)</th>
		<th>カラダ写真</th>
		<th></th>
		<th></th>
	</tr>
  <% @bodies.each do |body| %>
    <tr>
      <td><%= body.record_date.strftime('%Y/%m/%d') %></td>
      <td><%= body.weight %></td>
      <td><%= body.bfp %></td>
      <td><%= attachment_image_tag body, :image, :fill, 100, 100 %></td>
      <% if body.user_id == current_user.id %>
        <td><%= link_to '編集', edit_body_path(body.id), class: 'btn btn-outline-success' %></td>
        <td><%= link_to '削除', body_path(body.id), method: :delete, data: {confirm: "削除しますか？"}, class: 'btn btn-outline-danger' %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<%= paginate @bodies %>

app/views/bodies/new.html.erb
<h1>体組成 入力</h1>
<%= render 'bodies/form', body: @body %>