config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'my_page' => 'users#show', as: 'my_page'
  # resource :users, only: [:show] do
  #   collection do
  #     get "unsubscribe"
  #     patch "withdraw"
  #   end
  # end
  resources :trainings
  # 現状1対1のテーブルになってしまっているから不要
  # resources :training_details
  resources :bodies, except: [:show]
  resources :meals, except: [:show]
  resources :events, except: [:show]

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.new
    @events = Event.all
  end

  # def new
  # end

  def create
    event = Event.new(event_params)
    event.save
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    if event.update(event_params)
      flash[:notice] = "更新しました"
      redirect_to events_path
    else
      flash[:alert] = "もう一度入力してください"
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:notice] = "削除しました"
    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :body_part)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h2>種目編集</h2>
<%= form_with model:@event, local:true do |f| %>
  <div>
    <%= f.label :"種目名" %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :"部位" %>
    <%= f.select :body_part, Event.body_parts_i18n.keys.map{|k| [I18n.t("enums.event.body_part.#{k}"), k]} %>
  </div>
  <div>
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>種目</h1>

<h2>種目登録</h2>
<%= form_with model:@event, local:true do |f| %>
  <div>
    <%= f.label :"種目名" %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :"部位" %>
    <%= f.select :body_part, Event.body_parts_i18n.keys.map{|k| [I18n.t("enums.event.body_part.#{k}"), k]} %>
  </div>
  <div>
    <%= f.submit '登録' %>
  </div>
<% end %>

<h2>種目一覧</h2>
<% @events.each do |event| %>
  <div>
    <span>種目名</span>
    <%= event.name %>
  </div>
  <div>
    <span>部位</span>
    <%= event.body_part_i18n %>
  </div>
  <div>
    <%= link_to edit_event_path(event.id) do %>
      <button type="button" class="btn btn-success">編集</button>
    <% end %>
  </div>
    <div>
    <%= link_to event_path(event.id), method: :delete do %>
      <button type="button" class="btn btn-danger">削除</button>
    <% end %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>