config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'my_page' => 'users#show', as: 'my_page'
  # resource :users, only: [:show] do
  #   collection do
  #     get "unsubscribe"
  #     patch "withdraw"
  #   end
  # end
  resources :trainings
  # 現状1対1のテーブルになってしまっているから不要
  # resources :training_details
  resources :bodies, except: [:show]
  resources :meals, except: [:show]
  resources :events, except: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord

  belongs_to :user

  attachment :image

  validates :weight, presence: true
  validates :record_date, presence: true, uniqueness: true

end

app/models/meal.rb
class Meal < ApplicationRecord

  belongs_to :user
  has_many :meal_details, dependent: :destroy

  accepts_nested_attributes_for :meal_details, allow_destroy: true

  enum category: { breakfast: 0, lunch: 1, dinner: 2, snack: 3 }

  attachment :image

  validates :date, presence: true
  validates :category, presence: true

end

app/models/meal_detail.rb
class MealDetail < ApplicationRecord

  belongs_to :meal

  validates :name, presence: true
  validates :calory, presence: true
  validates :protein, presence: true
  validates :fat, presence: true
  validates :carb, presence: true

end

app/models/training.rb
class Training < ApplicationRecord

  has_many :training_details, dependent: :destroy

  accepts_nested_attributes_for :training_details, allow_destroy: true

  validates :training_date, presence: true

end

app/models/training_detail.rb
class TrainingDetail < ApplicationRecord

  belongs_to :training

  enum body_part: { chest: 0, back: 1, shoulder: 2, arm: 3, leg: 4, aerobic: 5, others: 6 }

  validates :weight, presence: true
  validates :repetition, presence: true
  validates :body_part, presence: true
  validates :training_name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bodies, dependent: :destroy
  has_many :meals, dependent: :destroy

  validates :name, presence: true
  # validates :sex, presence: true
  validates :birthday, presence: true
  validates :height, presence: true
  validates :weight, presence: true

  #refileが特定のカラムにアクセスするための記述
  attachment :profile_image

# パスワードなしでuser_edit
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  enum activity_level: { low: 0, middle: 1, high: 2 }
  enum purpose: { diet: 0, keep: 1, bulkup: 2 }

# ユーザーの年齢を計算するメソッド
  def age
    d1=self.birthday.strftime("%Y%m%d").to_i
    d2=Date.today.strftime("%Y%m%d").to_i
    return (d2 - d1) / 10000
  end

  # 基礎代謝計算式
  # The Basal Metabolic Rate (BMR)
  def calc_bmr
    if sex == true
      (10 * weight) + (6.25 * height) - (5 * age) + 5
    else
      (10 * weight) + (6.25 * height) - (5 * age) - 161
    end
  end

  # 一日あたりの活動代謝
  def calc_activity_metabolism
    if activity_level == "low"
      calc_bmr * 1.2
    elsif activity_level == "middle"
      calc_bmr * 1.55
    else
      calc_bmr * 1.725
    end
  end

  # 目的に合わせたカロリー設定
  def by_purpose
    if purpose == "diet"
      calc_activity_metabolism * 0.8
    elsif purpose == "keep"
      calc_activity_metabolism
    else
      calc_activity_metabolism * 1.2
    end
  end

  # 一日当たりのタンパク質（グラム表示）
  def protein_per_day
    weight * 2
  end

# 一日あたりの脂質（グラム表示）
  def fat_per_day
    by_purpose * 0.25 / 9
  end

# 一日あたりの炭水化物（グラム表示）
  def carb_per_day
    (by_purpose - (protein_per_day * 4 + by_purpose * 0.25)) / 4
  end


end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

  def index
    @bodies = Body.where(user_id: current_user.id).page(params[:page]).per(30).order("record_date ASC")
  end

  def new
    @body = Body.new
  end

  def create
    @body = Body.new(body_params)
    @body.user_id = current_user.id
    if @body.save
      flash[:notice] = "コミットでやんす!!"
      redirect_to bodies_path
    else
      flash[:alert] = "もう一度入力してください"
      render :new
    end
  end

  def edit
    @body = Body.find(params[:id])
  end

  def update
    @body = Body.find(params[:id])
    if @body.update(body_params)
      flash[:notice] = '更新しました'
      redirect_to bodies_path
    else
      flash[:alert] = 'もう一度入力してください'
      render :edit
    end
  end

  def destroy
    body = Body.find(params[:id])
    body.destroy
    flash[:notice] = '削除しました'
    redirect_to bodies_path
  end

  private
  def body_params
    params.require(:body).permit(:record_date, :weight, :bfp, :image)
  end

end

app/controllers/bodys_controller.rb
class BodysController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.new
    @events = Event.all
  end

  # def new
  # end

  def create
    event = Event.new(event_params)
    event.save
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    if event.update(event_params)
      flash[:notice] = "更新しました"
      redirect_to events_path
    else
      flash[:alert] = "もう一度入力してください"
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:notice] = "削除しました"
    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :body_part)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.where(user_id: current_user.id).page(params[:page]).per(30).order("date ASC")
  end

  def new
    @meal = Meal.new
    @meal.meal_details.build
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user_id = current_user.id
    if @meal.save
      flash[:notice] = '登録'
      redirect_to meals_path
    else
      flash[:alert] = 'もう一度入力してください'
      render :new
    end
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      flash[:notice] = "更新しました"
      redirect_to meals_path
    else
      flash[:alert] = "もう一度入力してください"
      render :edit
    end
  end

  def destroy
    meal = Meal.find(params[:id])
    meal.destroy
    flash[:notice] = "削除しました"
    redirect_to meals_path
  end

  private
  def meal_params
    params.require(:meal).permit(:date, :category, :image, meal_details_attributes:[:id, :name, :calory, :protein, :fat, :carb])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @training_details = TrainingDetail.all

    # todayの接種済みの数値を取得するための記述
    meals = Meal.where(user_id: current_user.id).where(date: Date.today)
    @calory = 0
    @protein = 0
    @fat = 0
    @carb = 0
    meals.each do |meal|
      # meal.meal_details.first
      # 現在は1対1の関係になってしまっているので、1行目のfirst
      @calory += meal.meal_details.first.calory
      @protein += meal.meal_details.first.protein
      @fat += meal.meal_details.first.fat
      @carb += meal.meal_details.first.carb
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>                             

app/views/layouts/_footer.html.erb
<footer>
  <p class="footer-text">© All rights reserved by Falcon8810</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!--navbar-light" style="background-color: #6600FF;-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <!--ナビバーロゴ-->
    <a class="navbar-brand p-2" href="/">
      <%= image_tag 'nyanko.png', size: "150x150", alt: "logo" %>
      <!--<span style="color: #fff;">筋トレマニアはひかれ合う</span>-->
    </a>
    <!--バーガー部分-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expand="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!--トグルメニュー中身-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!--ml-autoはmargin lightがauto-->
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item nav-link">
            <%= link_to "マイページ", my_page_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "筋トレ", trainings_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "トレーニング追加", new_training_path, class: "btn btn-outline-secondary" %>
          </li>

          <!--ドロップダウンメニュー仮-->
          <!--<li class="nav-item nav_link dropdown">-->
          <!--  <%#= link_to "筋トレ", "#", class: "nav-link dropdown-toggle", 'id': :'navbarDropdown', 'role': :'button', 'data-toggle': :'dropdown', 'aria-haspopup': :'true', 'aria-expanded': :'false' %>-->
          <!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
          <!--    <%#= link_to "筋トレ", trainings_path, class: "btn btn-outline-secondary dropdown-item" %>-->
          <!--    <%#= link_to "トレーニング追加", new_training_path, class: "btn btn-outline-secondary dropdown-item" %>-->
          <!--  </div>-->
          <!--</li>-->

          <li class="nav-item nav-link">
            <%= link_to "食事", meals_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "食事追加", new_meal_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "カラダ", bodies_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "カラダ追加", new_body_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "基本情報設定",  edit_user_registration_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
          <!--余裕があればここに<li class="nav-item dropdown"></li>-->
        <% else %>
          <li class="nav-item nav-link active">
            <%= link_to "top", root_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-secondary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PFC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>